name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Copia os arquivos do repositório
        uses: actions/checkout@v3

      - name: Instalar o Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.1'

      - name: Instalar o poetry
        run: pipx install poetry
        
      - name: Isntalar dependências
        run: poetry install
        
      - name: Executar testes
        run:  poetry run task test