name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Instalar o Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.1'